<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUaJD2xy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUaJD2xy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUaJD2xy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUaJD2xy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUaJD2xy\App_KernelDevDebugContainer([
    'container.build_hash' => 'UaJD2xy',
    'container.build_id' => '8b47aa43',
    'container.build_time' => 1624611723,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUaJD2xy');
