<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIsQx5sS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIsQx5sS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIsQx5sS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIsQx5sS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIsQx5sS\App_KernelDevDebugContainer([
    'container.build_hash' => 'IsQx5sS',
    'container.build_id' => 'ae5f9f88',
    'container.build_time' => 1624611033,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIsQx5sS');
